
name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
    tags: [ "v[0-9]+.[0-9]+.[0-9]+" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
        matrix:
          os: [ubuntu-22.04, windows-2022, macos-12]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: dist jacocoTestReport
          gradle-version: 7.5.1
          build-root-directory: ENG1

      - name: Upload JaCoCo coverage report as a workflow artefact.
        uses: actions/upload-artifact@v3.1.1
        with:
          name: jacoco-report-${{ matrix.os }}
          path: ENG1/tests/build/reports

      - name: Upload generated JAR
        uses: actions/upload-artifact@v3.1.1
        with:
          name: lib-${{ matrix.os }}.jar
          path: ENG1/desktop/build/libs/desktop-1.0.jar

      - name: Upload Checkstyle Report
        uses: actions/upload-artifact@v3.1.1
        if: startsWith(matrix.os, 'ubuntu')
        with:
          name: checkstyle-report
          path: ENG1/desktop/build/libs/reports

  release:
    runs-on: ubuntu-22.04
    needs: [ "build" ]
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write

    steps:
      - name: Download Ubuntu Build Artifact
        uses: actions/download-artifact@v3.0.1
        with: {name: lib-ubuntu-22.04.jar}
        run: mv lib.jar lib-ubuntu.jar

      - name: Download MacOS Build Artifact
        uses: actions/download-artifact@v3.0.1
        with: { name: lib-macos.jar }
        run: mv lib.jar lib-macos.jar

      - name: Download Windows Build Artifact
        uses: actions/download-artifact@v3.0.1
        with: { name: lib-windows-2022.jar }
        run: mv lib.jar lib-windows-2022.jar

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: lib.jar


